/**
 * SSOT for trend-informed content signal, generated by
 * scripts/trends/build-digest.mjs (weekly GitHub Action, PR-reviewed before
 * merge). Build-time only — no runtime fetch, no client tracker.
 */
import trendsData from './trends.json';

export type TrendSource = 'bluesky' | 'hackernews' | 'reddit';

export type TrendItem = {
  id: string;
  source: TrendSource;
  title: string;
  url: string;
  author?: string;
  publishedAt: string;
  tags: string[];
  score: number;
};

export const trends: TrendItem[] = trendsData.items as TrendItem[];
export const trendsGeneratedAt: string | null = trendsData.generatedAt;

export const sourceLabels: Record<TrendSource, string> = {
  bluesky: 'Bluesky',
  hackernews: 'Hacker News',
  reddit: 'Reddit',
};

export function topTrends(limit = 6): TrendItem[] {
  return [...trends].sort((a, b) => b.score - a.score).slice(0, limit);
}
