/**
 * SSOT for trend-informed content signal. Journal entries are generated by
 * scripts/trends/build-digest.mjs (daily GitHub Action) and auto-published to
 * src/content/journal/ — gate tests gate publication, no PR (D-022). Build-time
 * only — no runtime fetch, no client tracker.
 */
export type TrendSource = 'bluesky' | 'hackernews' | 'reddit' | 'github' | 'arxiv' | 'lobsters';

export type TrendItem = {
  id: string;
  source: TrendSource;
  title: string;
  url: string;
  author?: string;
  publishedAt: string;
  tags: string[];
  score: number;
  /** Hostname of the linked artifact, e.g. "github.com" */
  domain?: string;
  /** All sources this link surfaced on (corroboration) */
  sources?: TrendSource[];
  /** Self-hosted og:image thumbnail (/trends/{id}.webp), built at digest time */
  image?: string;
};

export const sourceLabels: Record<TrendSource, string> = {
  bluesky: 'Bluesky',
  hackernews: 'Hacker News',
  reddit: 'Reddit',
  github: 'GitHub',
  arxiv: 'arXiv',
  lobsters: 'Lobste.rs',
};

/** Display names + decorative accent per pillar tag (see scripts/trends/keywords.mjs). */
export const pillarMeta: Record<string, { label: string; color: string }> = {
  'on-device-ai': { label: 'On-device AI', color: '#4C6492' },
  'metal-ane': { label: 'Metal · ANE', color: '#631FCB' },
  'local-llm': { label: 'Local LLMs', color: '#E6524A' },
  'dsp-audio': { label: 'DSP · Audio', color: '#3C888F' },
  'ios-craft': { label: 'iOS craft', color: '#09A1D2' },
  'privacy-arch': { label: 'Privacy-first', color: '#C16223' },
};

export const fallbackPillar = { label: 'Signal', color: '#4C6492' };
